export const filterOptions = ['全部', '灵感', '人物', '章节', '续写', '风格', '工具'];

const defaultSkillBehaviorById = {
  'chapter-scenes': {
    panel: 'chapter-workflow',
    mode: 'scenes',
    input_label: '拆场要求',
    submit_label: '开始拆场',
  },
  'chapter-diagnose': {
    panel: 'chapter-workflow',
    mode: 'diagnose',
    input_label: '诊断要求',
    submit_label: '开始诊断',
  },
  'chapter-draft': {
    panel: 'chapter-workflow',
    mode: 'draft',
    input_label: '续写要求',
    submit_label: '开始续写',
  },
  'chapter-finalize': {
    panel: 'chapter-rewrite',
    mode: 'finalize',
    input_label: '改稿要求',
    submit_label: '开始定稿',
  },
  'chapter-polish': {
    panel: 'chapter-rewrite',
    mode: 'polish',
    input_label: '改稿要求',
    submit_label: '开始润色',
  },
  'chapter-humanize': {
    panel: 'chapter-rewrite',
    mode: 'humanize',
    input_label: '改稿要求',
    submit_label: '开始去 AI',
  },
};

function withSkillBehavior(skill) {
  const behavior = defaultSkillBehaviorById[skill.id];
  return behavior ? { ...skill, behavior } : skill;
}

export const skillSections = [
  {
    title: '核心技能',
    description: '围绕开书、卡文、整本推进和问题判断的主工具。',
    items: [
      {
        id: 'brainstorm',
        badge: '聊',
        name: '创意讨论',
        description: '像编辑一样和你多轮讨论当前问题，先把该解决的事说透。',
        category: '灵感',
        scenes: ['开书', '卡文', '方向'],
        accent: 'sand',
      },
      {
        id: 'blueprint',
        badge: '蓝',
        name: '蓝图生成',
        description: '把整本结构和章节推进重新排清楚，给出可写的章节蓝图。',
        category: '章节',
        scenes: ['蓝图', '主线', '章节'],
        accent: 'olive',
      },
      {
        id: 'architecture-stepper',
        badge: '构',
        name: '分步架构',
        description: '按模块逐步生成核心种子、人物、世界、骨架和蓝图，适合边改边写回。',
        category: '工具',
        scenes: ['架构', '分步', '续写'],
        accent: 'olive',
      },
      {
        id: 'continue-project',
        badge: '续',
        name: '续写扩展',
        description: '在现有项目基础上继续往后扩章，直接更新整本规划。',
        category: '续写',
        scenes: ['扩写', '后续', '整本'],
        accent: 'sand',
      },
      {
        id: 'consistency',
        badge: '检',
        name: '一致性检查',
        description: '检查人物动机、设定前后、空间时间和信息揭示顺序。',
        category: '人物',
        scenes: ['检查', '前后', '逻辑'],
        accent: 'slate',
      },
      {
        id: 'character-replica',
        badge: '像',
        name: '人物复刻',
        description: '提炼某个人物的判断框架、语气和边界，再按这个视角回答你的问题。',
        category: '人物',
        scenes: ['人物', '视角', '复刻'],
        accent: 'smoke',
        requires_project: false,
        requires_chapter: false,
      },
    ].map(withSkillBehavior),
  },
  {
    title: '章节工作流',
    description: '直接围绕当前章节处理拆场、生成、定稿和批量推进。',
    items: [
      {
        id: 'chapter-scenes',
        badge: '拆',
        name: '章节拆场',
        description: '把一章拆成 4 到 6 个场景，明确目标、冲突和转折。',
        category: '章节',
        scenes: ['场景', '结构', '钩子'],
        accent: 'olive',
      },
      {
        id: 'chapter-diagnose',
        badge: '诊',
        name: '章节诊断',
        description: '先判断这一章最该改哪里，适合卡在节奏、冲突或结尾时使用。',
        category: '章节',
        scenes: ['诊断', '节奏', '问题'],
        accent: 'slate',
      },
      {
        id: 'chapter-generate',
        badge: '写',
        name: '章节生成',
        description: '围绕当前章节上下文生成一版可直接保存的正文。',
        category: '章节',
        scenes: ['正文', '初稿', '推进'],
        accent: 'sand',
      },
      {
        id: 'chapter-draft',
        badge: '续',
        name: '续写正文',
        description: '沿着当前章节状态继续往下写，适合已经有场景方向时直接开写。',
        category: '续写',
        scenes: ['续写', '正文', '承接'],
        accent: 'sand',
      },
      {
        id: 'chapter-finalize',
        badge: '定',
        name: '定稿整理',
        description: '把当前章节整理成更完整的稿子，收紧结构和重复信息。',
        category: '章节',
        scenes: ['定稿', '重写', '结构'],
        accent: 'slate',
      },
      {
        id: 'chapter-polish',
        badge: '润',
        name: '场景润色',
        description: '加强对白、画面和节奏，不改大方向，只改读感。',
        category: '风格',
        scenes: ['润色', '对白', '节奏'],
        accent: 'smoke',
      },
      {
        id: 'chapter-humanize',
        badge: '人',
        name: '去 AI',
        description: '按去痕规则压掉模板腔和说明腔，并给出前后评分变化。',
        category: '风格',
        scenes: ['去AI', '语气', '自然'],
        accent: 'smoke',
      },
      {
        id: 'batch-generate',
        badge: '批',
        name: '批量生成',
        description: '连续生成多个章节并自动写回项目，适合快速铺量。',
        category: '续写',
        scenes: ['批量', '多章', '连写'],
        accent: 'olive',
      },
    ].map(withSkillBehavior),
  },
  {
    title: '风格与工具',
    description: '把文风、提示词、项目文件和运行记录都收进当前技能区。',
    items: [
      {
        id: 'style-dna',
        badge: '风',
        name: '文风与DNA',
        description: '分析样文、融合文风、维护作者参考库，并保存成可复用方案。',
        category: '风格',
        scenes: ['文风', 'DNA', '参考'],
        accent: 'smoke',
      },
      {
        id: 'prompt-presets',
        badge: '词',
        name: '提示词方案',
        description: '管理不同写作预设，切换当前全局提示词策略。',
        category: '工具',
        scenes: ['预设', '提示词', '切换'],
        accent: 'slate',
      },
      {
        id: 'xp-presets',
        badge: 'XP',
        name: 'XP 预设',
        description: '存放偏好的戏感方向，比如悬疑推进、人物拉扯、反转控制。',
        category: '工具',
        scenes: ['XP', '偏好', '强化'],
        accent: 'sand',
      },
      {
        id: 'knowledge-search',
        badge: '知',
        name: '知识检索',
        description: '直接在技能区里导入资料、检索设定和正文片段。',
        category: '工具',
        scenes: ['资料', '检索', '设定'],
        accent: 'olive',
      },
      {
        id: 'web-research',
        badge: '考',
        name: '联网考据',
        description: '查询历史典故、史实出处和可借鉴的写作素材。',
        category: '工具',
        scenes: ['典故', '史实', '联网'],
        accent: 'slate',
      },
      {
        id: 'reader',
        badge: '读',
        name: '小说阅读',
        description: '按章节顺着读当前项目正文，不切出技能页也能通读。',
        category: '工具',
        scenes: ['阅读', '章节', '通读'],
        accent: 'slate',
      },
      {
        id: 'file-browser',
        badge: '文',
        name: '文件浏览',
        description: '查看项目里的设定文件、章节文件和导出文件。',
        category: '工具',
        scenes: ['文件', '查看', '项目'],
        accent: 'slate',
      },
      {
        id: 'logs',
        badge: '志',
        name: '运行日志',
        description: '查看 backend 当前日志，出问题时直接在这里看。',
        category: '工具',
        scenes: ['日志', '排查', '运行'],
        accent: 'slate',
      },
      {
        id: 'prompt-history',
        badge: '史',
        name: 'Prompt 历史',
        description: '查看模型请求和返回记录，便于复盘和调预设。',
        category: '工具',
        scenes: ['历史', 'Prompt', '复盘'],
        accent: 'smoke',
      },
    ].map(withSkillBehavior),
  },
];
